### ISSUE TITLE
Unable to override defaultProps on a case-by-case basis

### ISSUE THREAD

**Issue by joemckie** [stowball/react-native-svg-icon#1]
When `SvgIcon.defaultProps.viewBox` is set, it's not possible to use the `viewBox` property in the icon file.

E.g.:

```javascript
/* Icon.js */

import React from 'react';
import SvgIcon from 'react-native-svg-icon';

SvgIcon.defaultProps.viewBox = '0 0 24 24';

const Icon = props => <SvgIcon {...props} svgs={/* ... */} />;

export default Icon;

```

```javascript
/* icon.svg */

import React from 'react';
import { Path } from 'react-native-svg';

export default {
  svg: /* ... */,
  viewBox: '131 0 59 59',
};

```

IMO the second viewBox should take priority, as it's for a specific icon.

Alongside checking whether `props.viewBox` is set, it might be worth also checking to see whether the value differs from the `defaultProps` value?

**Comment by stowball** [comment]
Hmmm, yeah. It's [actually documented this way](https://github.com/stowball/react-native-svg-icon/blame/master/README.md#L85), but I agree, it's probably not useful for real-world scenarios.

Ideally, the specificity order should be:
1. `<Icon viewBox />`
2. `{ Name: { viewBox: '' } }`
3. `Icon.defaultProps.viewBox`
4. `SvgIcon.defaultProps.viewBox`

The problem is that, AFAIK, there's no way of knowing if a prop's value is set from `defaultProps` or on a component instance like `<Icon viewBox="0 0 10 10" />`. So, to achieve this, I'd have to use a separate prop for the `viewBoxDefault`, which is overridable by `viewBox`.

Do you think this would be confusing? Because believe it or not, it's what [I implemented in v0.2.0](https://github.com/stowball/react-native-svg-icon/commit/5ebfa0ccef4926eaf2f995124f997390883f5090#diff-6493b3f6c6ae311cd0f4d8ec7d8d6e33), but I didn't like it 😕

Unless you know of a better workaround? (I'm still pretty new to React really as well)

**Comment by joemckie** [comment]
`defaultProps` and `props` are different, so you should be able to compare between the two. If they're the same, the value hasn't been overridden.

I think that's the case, anyhow. I'll take a look at doing a PR over the weekend - tests are lacking so I could probably add some of them in too :)

**Comment by stowball** [comment]
That would be much appreciated. I tried to implement tests with Mocha and Enzyme, but ran in to issue after issue trying to import the dependencies (`reserved word`)

**Comment by joemckie** [comment]
@stowball I'm just coming across this again as it came up again in my project. Is it something you still need a hand with? Can find some time this weekend if so.

**Comment by stowball** [comment]
Done. Your solution didn't quite work and Dan Abramov confirmed that it wasn't possible to differentiate props from defaultProps, so went with a `defaultViewBox` prop
